# Generated by Django 5.1.2 on 2024-10-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresaGimnasio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='creado',
        ),
    ]
